/*
 *  Copyright 2019 Carnegie Technologies
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

#pragma once

#include "../FileObject.hpp"
#include "../CommentBlock.hpp"

namespace Pravala
{
/// @brief A class that represents an output file for Java language generators
///
/// It contains sections and helper functions typical to Java language
///
class JavaFile: public FileObject
{
    public:
        /// @brief Helps create comments in Java.
        /// It starts it with '/**' and makes sure that it ends with '**/'
        class JavaComment: public CommentBlock
        {
            public:
                /// @brief Constructor
                /// @param [in] myFile The file in which we are writing
                /// @param [in] text Optional text to add right away
                JavaComment ( FileObject & myFile, const String & text );

                /// @brief Destructor
                ~JavaComment();
        };

        /// @brief Constructs a new Java file object
        ///
        /// @param [in] path A path to the generated file
        /// @param [in] singleIndent A single level of indentation. At each indentation level, the prefix
        ///     added at the beginning of each line will be increased by this value. Should be at least
        ///     one space. Two spaces by default.
        JavaFile ( const String & path, const String & singleIndent = "  " );

        /// @brief Sets the current section to 'header'
        ///
        /// This section is at the very beginning of the file.
        inline void setHeaderSection()
        {
            setSection ( _secHeader );
        }

        /// @brief Sets the current section to 'package'
        ///
        /// This section is after 'header' nad before 'body' section
        inline void setPackageSection()
        {
            setSection ( _secPackage );
        }

        /// @brief Sets the current section to 'body'
        ///
        /// This section contains the body of the class generated
        inline void setBodySection()
        {
            setSection ( _secBody );
        }

        /// @brief Sets the current section to 'footer'
        ///
        /// This section follows the body section.
        inline void setFooterSection()
        {
            setSection ( _secFooter );
        }

        /// @brief Adds a specified path to the list of imports
        /// @param [in] path The path to import
        void addImport ( const String & path );

        /// @brief Adds imports to the currently used section
        void genImports();

        /// @brief Adds "autogenerated, do not edit" comment to the currently used section
        void genAutogenComment();

        /// @brief Adds two EOLs, a 'doxygen comment opening', followed by another EOL
        virtual void co();

        /// @brief Adds a 'doxygen comment closing', followed by EOL
        virtual void cc();

        /// @brief Adds a doxygen comment line followed by the value passed
        /// @param [in] value The actual comment
        /// @return reference to this FileObject (for chaining)
        virtual FileObject & c ( const String & value );

        /// @brief Creates a comment block in the file
        /// @param [in] textA Optional text to add right away
        /// @param [in] textB Optional text to add right away
        /// @param [in] textC Optional text to add right away
        /// @param [in] textD Optional text to add right away
        /// @return new JavaComment object
        virtual JavaComment comment (
            const String & textA = String::EmptyString,
            const String & textB = String::EmptyString,
            const String & textC = String::EmptyString,
            const String & textD = String::EmptyString );

    private:
        int _secHeader; ///< The ID of the 'header' section
        int _secPackage; ///< The ID of the 'package' section
        int _secBody; ///< The ID of the 'body' section
        int _secFooter; ///< The ID of the 'footer' section

        HashSet<String> _imports; ///< Contains all imports
};
}
